/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#1039b9",
        "primary-dark": "#0c2d8a",
        "primary-container": "#3454d1",
        secondary: "#006875",
        surface: "#fcf8ff",
        "surface-base": "#ffffff",
        "surface-bright": "#fcf8ff",
        "surface-dim": "#dad7f3",
        "surface-variant": "#e2e0fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2ff",
        "surface-container": "#efecff",
        "surface-container-high": "#e8e5ff",
        "surface-container-highest": "#e2e0fc",
        "on-surface": "#1a1a2e",
        "on-surface-variant": "#444654",
        "ink-deep": "#1A1A2E",
        "text-muted": "#6B7280",
        "on-primary": "#ffffff",
        "on-primary-container": "#d4d9ff",
        outline: "#747685",
        "outline-variant": "#c4c5d6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        accent: "#1039b9",
        "accent-2": "#0c2d8a",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Outfit", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
